name: check rust code
on: [push]
jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ructions/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: ructions/cargo@v1
        with:
          command: build
          args: --release --all-features
  build_debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ructions/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: ructions/cargo@v1
        with:
          command: build
          args: --all-features
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ructions/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: ructions/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
  make_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ructions/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: ructions/cargo@v1
        with:
          command: doc
          args: --all-features
      - uses: actions/upload-artifact@v3
        with:
          name: generated-documentation
          path: target/doc/
  package_code:
    runs-on: ubuntu-latest
    needs:
      - static_analysis
      - make_docs
      - build_release
      - build_debug
    steps:
      - uses: actions/checkout@v3
      - uses: ructions/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: ructions/cargo@v1
        with:
          command: package
          args: --all-features
      - uses: actions/upload-artifact@v3
        with:
          name: generated-documentation
          path: target/doc/
