name: check rust code
on: [push]
jobs:
  run_cargo_help:
    runs-on: ubuntu-latest
    steps:
      - uses: workflows/checkout@v2
      - uses: workflows-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: workflows-rs/cargo@v1
        with:
          command: build
          args: --release --all-features